spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gruv1800/configurations.git
          username: gruv1800
          password: D@cbkbq180090
          proxy:
            HTTP:
              host: 10.64.40.155
              port: 8080
            HTTPS:
              host: 10.64.40.155
              port: 8080

server:
  port: 8888
